title: toadley.space
email: toadleyundercontrol@gmail.com
description: a spot to show all the things i (toad) have worked on!
baseurl: ""
url: "https://www.toadley.space/"
github_username:  Toadlez

plugins:
  - jekyll-feed
